- name: play1
  hosts: prod
  tasks:
    - name: task1 of play1
      ansible.builtin.debug:
        msg: "Hello world"


- name: play2
  hosts: dev
  tasks:
    - name: task1 of play2
      ansible.builtin.debug:
        msg: "Hi my world"      