- name: Configuring hostname
  ansible.builtin.shell: set-hostname {{ component }}

- name: disabling the default nodejs version
  ansible.builtin.shell: dnf module disable nodejs -y
 
- name: installing node js
  ansible.builtin.dnf:
   name: nodejs
   state: present

- name: creating {{ app user }} app user 
  ansible.builtin.user:
    name: "{{ app_user }}"

- name: copy the {{ component }} systemd file
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: deleting the old {{ component }} directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: absent

- name: Creating the old {{ component }} directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory

- name: download and extracting {{ component }} code
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: "{{ app_dir }}"
    remote_src: yes

- name: Installing mysql client
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Generation {{ component }} artifacts
  community.general.npm:
    path: "{{ app_dir }}"

    


- name: Restarting nginx
  ansible.builtin.service: 
    name: nginx
    state: restarted
    enabled: yes