- name: Configuring hostname
  ansible.builtin.shell: set-hostname {{ component }}

- name: Installing {{ component }}
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Starting mysqld
  ansible.builtin.service: 
    name: mysqld
    state: started
    enabled: yes