- name: Configuring hostname
  ansible.builtin.shell: set-hostname {{ component }}

- name: Installing {{ component }}
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Starting mysqld
  ansible.builtin.service: 
    name: mysqld
    state: started
    enabled: yes

- name: Resetting the password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1